Repository wiremock/wiremock-testcontainers-go, pull requests merged in 2023-08, with the labels that each got.

#20 Fix formatting and add missing link in quickstart.md
  docs/quickstart.md
Labels: documentation

#22 Grant Release Drafter permission to create new releases
  .github/workflows/changelog-draft.yml
Labels: chore

#24 Update testcontainers-go to v0.22.0 to fix compatibility with Golang 1.20.6 and 1.19.11
  .github/workflows/go.yml
  go.mod
  go.sum
Labels: enhancement

#25 Fix the release trigger
  .github/workflows/release.yml
Labels: chore

#28 Update the Module version in the tutorial
  docs/quickstart.md
  examples/quickstart/go.mod
Labels: documentation

#31 Fix typo in the references
  README.md
Labels: documentation

#30 Add a `testcontainers_wiremock#RunContainerAndStopOnCleanup()` method to simplify automatic termination
  examples/quickstart/quickstart_test.go
  tc-wiremock.go
Labels: enhancement
