Repository wiremock/wiremock-testcontainers-go, pull requests merged in 2023-07, with the labels that each got.

#5 Minor linting tweaks
  README.md
  go.mod
  go.sum
  tc-wiremock_test.go
Labels: chore

#7 Use the official WireMock Docker image by default
  .github/workflows/go.yml
  Dockerfile
  Makefile
  README.md
  tc-wiremock.go
Labels: enhancement

#8 Add Release Drafter to the repository
  .github/release-drafter.yml
  .github/workflows/changelog-draft.yml
Labels: chore

#13 Add references to WireMock and Testcontainers resources
  README.md
Labels: documentation

#10 Publish documentation to go.dev when doing the release
  .github/workflows/release.yml
Labels: chore

#11 Change the release Drafter template to follow the versioning requirement
  .github/release-drafter.yml
Labels: chore

#12 Add GoDoc badge
  README.md
Labels: documentation

#14 Fix module defition in go.mod
  go.mod
Labels: chore

#15 Fix the go.dev packaging script
  .github/workflows/release.yml
Labels: chore

#16 Add the Quick Start guide
  README.md
  docs/images/quickstart.gif
  docs/quickstart.md
  examples/quickstart/README.md
  examples/quickstart/go.mod
  examples/quickstart/go.sum
  examples/quickstart/hello-world.json
  examples/quickstart/quickstart_test.go
Labels: documentation
