Repository wiremock/wiremock-testcontainers-go, pull requests merged in 2025-05, with the labels that each got.

#48 Change RunDefaultContainerAndStopOnCleanup to use the interface testing.TB
  tc-wiremock-v3_test.go
  tc-wiremock.go
Labels: enhancement

#54 Dependabot: Use "chore" label for Actions updates
  .github/dependabot.yml
Labels: chore

#55 Update dependencies in the examples
  examples/quickstart-v3/README.md
  examples/quickstart-v3/go.mod
  examples/quickstart-v3/go.sum
  examples/quickstart/README.md
  examples/quickstart/go.mod
  examples/quickstart/go.sum
  examples/using_api_client/README.md
  examples/using_api_client/go.mod
  examples/using_api_client/go.sum
Labels: dependencies
